# Generated by Django 5.0.1 on 2024-01-14 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('number_of_rounds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='date_time',
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tournament_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liga.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.tournamenttype'),
        ),
    ]
