# Generated by Django 5.0.1 on 2024-01-14 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0003_alter_match_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='location',
        ),
        migrations.AddField(
            model_name='match',
            name='ranking',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ranking',
            field=models.CharField(default=1, max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Apenas letras, números e espaços são permitidos.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Apenas letras, números e espaços são permitidos.')]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Apenas letras, números e espaços são permitidos.')]),
        ),
    ]
