# Generated by Django 5.0.1 on 2024-01-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0004_remove_tournament_location_match_ranking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='ranking',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_rounds',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('points', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='tournaments_participated', through='liga.TournamentResult', to='liga.player'),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
