# Generated by Django 5.0.1 on 2024-01-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0006_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='points',
            new_name='total_points',
        ),
        migrations.RenameField(
            model_name='tournamentresult',
            old_name='ranking',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='ranking',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='liga.player'),
        ),
    ]
