# Generated by Django 5.0.1 on 2024-01-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0007_rename_points_ranking_total_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='number_of_players',
            field=models.IntegerField(default=1),
        ),
    ]
