# Generated by Django 5.0.1 on 2024-01-26 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0010_remove_deck_player_remove_deck_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentresult',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liga.deck'),
        ),
    ]
