# Generated by Django 5.0.6 on 2024-06-16 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0013_yourmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.tournamenttype'),
        ),
    ]
