# Generated by Django 5.0.6 on 2024-06-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0014_alter_tournament_tournament_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
