# Generated by Django 5.0.6 on 2024-06-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0016_alter_deck_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='image',
            field=models.ImageField(default='default_deck_image.jpg', upload_to='deck_images/'),
        ),
    ]
