# Generated by Django 5.0.6 on 2024-06-22 19:42

import liga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0017_alter_deck_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='image',
            field=models.ImageField(default='default_deck_image.jpg', upload_to=liga.models.deck_image_path),
        ),
    ]
